<a href="https://colab.research.google.com/github/241255/Prog2kakushin/blob/main/work2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import csv
from google.colab import files

#ファイルの読み込み
uploaded = files.upload()
uploaded = files.upload()
uploaded = files.upload()
data = pd.read_csv("./data.csv", header=None)
data2 = pd.read_csv("./data2.csv", header=None)

#データの読み込み
array = np.array
array = data.values
array2 = np.array
array2 = data2.values

print('行列1')
print(array)
print('\n')
print('行列2')
print(array2)
print('\n')

#行列の計算
print('求めたい結果を選択してください')
print(1,'加算')
print(2,'減算')
print(3,'乗算')
print(4,'除算','\n')

while True:
  a = int(input())
  if a == 1:
    r = array + array2
    print('加算結果')
    print(r)
    break
  if a == 2:
    r = array - array2
    print('減算結果')
    print(r)
    break
  if a == 3:
    r = array * array2
    print('乗算結果')
    print(r)
    break
  if a == 4:
    r = array / array2
    print('除算結果')
    print(r)
    break
  else:
    print('再度入力しなおしてください')

#結果をファイルに書き出し
with open("r_data.csv", "w") as f:
    csv_w = csv.writer(f, lineterminator='\n')
    csv_w.writerows(r)

Saving data.csv to data.csv


Saving data2.csv to data2.csv


Saving r_data.csv to r_data.csv
行列1
[[11  5  1]
 [ 5  9  6]
 [ 0  2 13]]


行列2
[[ 0  9 11]
 [ 7  4 16]
 [10  8  5]]


求めたい結果を選択してください
1 加算
2 減算
3 乗算
4 除算 

3
乗算結果
[[ 0 45 11]
 [35 36 96]
 [ 0 16 65]]
